### ISSUE TITLE
Integrate 'libusb' and 'rtl-sdr' library modifications with original projects

### ISSUE THREAD

**Issue by videgro** [martinmarinov/rtl_tcp_andro-#10]
Dear mr. Marinov,

I very appreciate the changes you made in 'libusb' and 'rtl-sdr' to let it work at an Android device!

I would really like it when you are able to get your modifications integrated in the original projects. Or at least rebase your modifications on the master-branche of the 'libusb' and 'rtl-sdr' projects.

In the original 'libusb'-project there is even Android-support included. Maybe you can use that lib without modifications?

Thanks in advance!

Many greetings,
 Vincent

As reference, these are the locations of the original projects:
https://github.com/libusb/libusb.git
https://github.com/keenerd/rtl-sdr.git

**Comment by martinmarinov** [comment]
Hey Vincent,

I am afraid this would be impossible for two main reasons:

* The modifications of libusb that is used in this project disables a number of features (hotplug detection being one of them). This is required due to the permission model of Android and the fact that starting Android 6.0 it is much more strict so some libusb features are practically impossible without root.
* The modifications of rtl-sdr are so that it could be used with the modified version of libusb. If the libusb modifications cannot be merged into the master project, then we can't merge rtl-sdr either.

Yes, there is libusb support for Android, but it is only under root. Having libusb support without root requires Android java code and modifications to disable some libusb features that are not compatible with the Android security model.

If you figure out a way to push these changes upstream I would be really happy to assist. However I currently really don't see a technically feasible way to do this without a major refactor of both libusb/rtl-sdr and reducing their capabilities.

**Comment by videgro** [comment]
Thanks for your reply.

Maybe as first step you may try to convince the 'libusb'-team that Android-support is not complete when it's not possible to use USB-devices on Android-devices without root permissions. Maybe some kind of compile-time switch can be used to enable your changes on the master branch of libusb. Have you ever tried to submit a pull-request to the libusb-project? By the way, you know that you are a bit behind the HEAD of the libusb-project? 

For you it would also be much easier to just depend on the 'libusb'-project instead of maintaining your own fork. In that way changes/bugfixes are maintained by the libusb-community. I think it's unnecessary to sum up all the benefits for you.

Another possibility to ease maintenance a bit would be to fork the libusb and rtl-sdr projects to their own GIT-hub projects so that CHANGES relative to their 'mother-projects' would be easily traceable by GIT.

**Comment by videgro** [comment]
I forked the projects: libsusb and rtl-sdr and submitted on each of them one commit with the changes you made to these libs. Changes are at the 'android_mods'-branch.

You can find the repos here:
https://github.com/videgro/libusb
https://github.com/videgro/rtl-sdr

You are free to use/contribute to these GIT repositories or even I can transfer ownership to you if you wish.

In GIT you can use them as so called submodules of another GIT project:
https://github.com/blog/2104-working-with-submodules

By the way it seems that the 'RTL-SDR.com Silver dongle' crashes with these versions of the repos. I tried to make the commits as small/lean as possible. Maybe I missed some essential part(s). By the way tested with two different sticks which are identified as: '0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T' without problems.

Many greetings,
 Vincent

**Comment by martinmarinov** [comment]
Hey Vincent,

Many thanks for your invitation to contribute.

However my bandwidth is very limited at the moment and I can't spend additional development time on this particular request.

I am willing to look at pull requests or patches that you might have for the Android driver.

Martin
