### ISSUE TITLE
Missing android.permission.sec.MDM_APP_MGMT

### ISSUE THREAD

**Issue by MaPePeR** [martinmarinov/rtl_tcp_andro-#11]
The driver app does not request the required permissions properly with the latest version from the google play store. (Testing on a  SM-T533 with Android 5.1.1)

```
RtlSdr: found 1 device opening options
Only 1 option available, no need to ask user. Opening rtl-sdr /dev/bus/usb/001/002
Queueing
Arguments SdrTcpArguments{gain=24, samplerateHz=1024000, frequencyHz=100000000, address='127.0.0.1', port=60187, ppm=0}
Starting service with device rtl-sdr /dev/bus/usb/001/002
Caught exception SecurityException: Admin  does not have android.permission.sec.MDM_APP_MGMT
 -> Parcel  -> IUsbManager$Stub$Proxy  -> UsbManager  -> UsbPermissionObtainer  -> RtlSdrDevice  -> RtlSdrDevice$1
Closed service due to exception SecurityException: Admin  does not have android.permission.sec.MDM_APP_MGMT
Closing service
```

**Comment by MaPePeR** [comment]
Upon further investigation it looks like this is a samsung specific problem with android 5.1.1:

http://developer.samsung.com/forum/thread/-android-usb-scanner-not-working-on-samsung-galaxy-j2/201/296041?boardName=SDK&startId=zzzzz~&searchSubId=0000000028

**Comment by martinmarinov** [comment]
I agree. It seems like it is very Samsung 5.1.1 specific issue and there is no known workaround at the moment.

I guess we hope Samsung releases an update to address this.

**Comment by abhishekkumar1902** [comment]
Something strange is happening with my case. I am using Samsung note edge running Android v5.1.1. I, where I compiled all the 9 uvccamera projects and tested on the phone and it was successfully able to detect the camera and fetch the video from the camera as well. Now, just what I did is just copied the same code and layout widget design from **usbCameraTest0** project line by line without any modification and integrated it into a new project targeted at **same compiler, API and SDK level**. There happens no problems in compilation and starting of this new app but the problem is that now when I press the "connect to" camera button, the dialog box comes in but it does not detect the camera at all. Please help me with this issue. At the same time, if I run the usbCameraTest0 project alone, it runs fine. Not sure what could be wrong. Please help.
